// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMR000yLCARZ8U_6QLFy4UJ2lLXnLG_ts',
    appId: '1:493887585590:web:c3b8f3b1a344d28d10c797',
    messagingSenderId: '493887585590',
    projectId: 'majara-388b5',
    authDomain: 'majara-388b5.firebaseapp.com',
    storageBucket: 'majara-388b5.firebasestorage.app',
    measurementId: 'G-GD3ZCXX083',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxW9ATY-Ql0QABsY-psGyJvOr5dBXS4A0',
    appId: '1:493887585590:android:3a8b9e439476b55f10c797',
    messagingSenderId: '493887585590',
    projectId: 'majara-388b5',
    storageBucket: 'majara-388b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgbFwrkg-g71UO6wyoC5r54p_CoVZdXo',
    appId: '1:493887585590:ios:9b7fb2547be5307f10c797',
    messagingSenderId: '493887585590',
    projectId: 'majara-388b5',
    storageBucket: 'majara-388b5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlgbFwrkg-g71UO6wyoC5r54p_CoVZdXo',
    appId: '1:493887585590:ios:9b7fb2547be5307f10c797',
    messagingSenderId: '493887585590',
    projectId: 'majara-388b5',
    storageBucket: 'majara-388b5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMR000yLCARZ8U_6QLFy4UJ2lLXnLG_ts',
    appId: '1:493887585590:web:0523dc503a1ae92210c797',
    messagingSenderId: '493887585590',
    projectId: 'majara-388b5',
    authDomain: 'majara-388b5.firebaseapp.com',
    storageBucket: 'majara-388b5.firebasestorage.app',
    measurementId: 'G-V3M66W3WGB',
  );
}
